/** Browsing categories for the stock list. Jupiter has no sectors, so tickers are mapped by hand */
export const STOCK_CATEGORIES = [
  { id: 'pre-ipo', label: 'Pre-IPO' },
  { id: 'ai', label: 'AI & chips' },
  { id: 'tech', label: 'Tech' },
  { id: 'fintech', label: 'Fintech & crypto' },
  { id: 'index', label: 'Index funds' },
  { id: 'finance', label: 'Banks' },
  { id: 'health', label: 'Health' },
  { id: 'consumer', label: 'Consumer' },
  { id: 'energy', label: 'Energy & metals' },
  { id: 'industrial', label: 'Industrials' },
  { id: 'other', label: 'Other' },
] as const

export type StockCategory = (typeof STOCK_CATEGORIES)[number]['id']

/** Pre-IPO shares are known by where they come from, not their ticker, so the catalog sets it */
const GROUPS: Record<Exclude<StockCategory, 'other' | 'pre-ipo'>, string[]> = {
  ai: [
    'NVDA',
    'AMD',
    'AVGO',
    'MRVL',
    'TSM',
    'SKHY',
    'MU',
    'ASML',
    'INTC',
    'ARM',
    'ALAB',
    'CBRS',
    'SMCI',
    'QCOM',
    'SNDK',
    'AAOI',
    'CRWV',
    'NBIS',
    'PLTR',
    'BOT',
    'SOXL',
    'SMH',
    'QUBT',
    'DRAM',
  ],
  tech: [
    'AAPL',
    'MSFT',
    'GOOGL',
    'META',
    'AMZN',
    'NFLX',
    'ORCL',
    'IBM',
    'CSCO',
    'CRM',
    'ADBE',
    'ACN',
    'CRWD',
    'APP',
    'NET',
    'NOW',
    'HPE',
    'DELL',
    'UBER',
    'RBLX',
    'TTWO',
    'ASTS',
    'TSLA',
    'CMCSA',
    'OPEN',
    'BSP',
    'BABA',
    'SHOP',
    'SNAP',
    'RDDT',
    'GRND',
    'RUM',
    'BB',
    'GPRO',
    'DJT',
    'XYZ',
  ],
  fintech: [
    'CRCL',
    'HOOD',
    'COIN',
    'MSTR',
    'STRC',
    'STRK',
    'SATA',
    'BMNR',
    'SBET',
    'RIOT',
    'MARA',
    'CLSK',
    'GLXY',
    'BTGO',
    'IREN',
    'CORZ',
    'BTBT',
    'DFDV',
    'KRAQ',
    'PYPL',
    'V',
    'MA',
    'BULL',
    'CYPH',
  ],
  index: [
    'SPY',
    'QQQ',
    'VTI',
    'VT',
    'VOO',
    'IWM',
    'IJR',
    'SCHF',
    'IEMG',
    'VXUS',
    'TQQQ',
    'XLE',
    'XOP',
    'URA',
    'MOO',
    'COPX',
    'NLR',
    'GDX',
    'TBLL',
    'VCX',
    'SCHH',
  ],
  finance: ['JPM', 'BAC', 'GS', 'BRK.B'],
  health: [
    'UNH',
    'NVO',
    'LLY',
    'AZN',
    'ABT',
    'PFE',
    'MRK',
    'TMO',
    'JNJ',
    'ABBV',
    'MRNA',
    'DHR',
    'ALNY',
    'HIMS',
    'PTN',
  ],
  consumer: [
    'MCD',
    'KO',
    'GME',
    'WMT',
    'PEP',
    'PG',
    'PM',
    'JMKE',
    'COST',
    'NKE',
    'LULU',
    'AMC',
    'DKNG',
    'MGM',
    'WEN',
    'DNUT',
    'BROS',
    'FLWS',
    'SPHR',
    'HTZ',
  ],
  energy: ['XOM', 'CVX', 'CEG', 'LIN', 'UUUU', 'USAR', 'BE', 'OKLO', 'GLD', 'SLV', 'PPLT'],
  industrial: ['HON', 'LMT', 'DE', 'SPCX', 'UPS', 'LUV', 'BA', 'FLY', 'WULF', 'RIVN'],
}

const BY_TICKER = new Map(
  Object.entries(GROUPS).flatMap(([category, tickers]) =>
    tickers.map((ticker) => [ticker, category as StockCategory] as const),
  ),
)

export function categoryFor(ticker: string): StockCategory {
  return BY_TICKER.get(ticker.toUpperCase()) ?? 'other'
}
